routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('candidates', 'CandidatesController')->middleware('auth');

Route::resource('users', 'UsersController')->middleware('auth');

Route::resource('cars', 'CarsController')->middleware('auth');
Route::get('cars/changecategory/{id}/{cid}', 'CarsController@changeCategory')->name('cars.changecategory');

Route::resource('customers', 'CustomersController')->middleware('auth');


Route::get('candidates/changeuser/{cid}/{uid?}', 'CandidatesController@changeUser')->name('candidate.changeuser');
Route::get('candidates/changestatus/{cid}/{sid}', 'CandidatesController@changeStatus')->name('candidates.changestatus')->middleware('auth');

Route::post('candidates/changestatus/', 'CandidatesController@changeStatusFromCadidate')->name('candidates.changestatusfromcandidate')->middleware('auth');

Route::get('mycandidates', 'CandidatesController@myCandidates')->name('candidates.mycandidates')->middleware('auth');

Route::get('statuses', 'CandidatesController@statuses')->name('candidates.statuses');

Route::get('candidatesbyage', 'CandidatesController@candidatesByAge')->name('candidates.candidatesbyage')->middleware('auth');

Route::get('candidates/delete/{id}', 'CandidatesController@destroy')->name('candidate.delete');

Route::get('users', 'CandidatesController@showUsers')->name('candidate.users')->middleware('auth');

Route::get('users/delete/{uid}', 'UsersController@destroy')->name('users.delete');

Route::get('users/changemessi/{uid}', 'UsersController@changeMessi')->name('users.changemessi')->middleware('auth');


Route::get('/hello', function (){
    return 'Hello Larevel';
}); 

Route::get('/student/{id}', function ($id  = 'No student found'){
    return 'We got student with id '.$id;
});

Route::get('/car/{id?}', function ($id  = null){
    if(isset($id)){
        //TODO: validate for integer  
        return "We got car $id";
    } else {
        return 'We need the id to find your car';
    }
});


Route::get('/comment/{id}', function ($id) {
    return view('comment', compact('id'));
});

// Route::get('/users/{email}/{name?}', function ($email,$name = null) {
//     if(!isset($name)){
//         $name = 'Mising name';
//     }
//     return view('users', compact('email','name'));
// });




#example
Route::get('/users1/{name?}/{email}', function ($name = null, $email) {
    if(!isset($name)){
        $name = 'Mising name';
    }
    return view('users', compact('email','name'));
});























Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Candidate.php
<?php

namespace App;


use Illuminate\Support\Enumerable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Candidate extends Model
{
    protected $fillable = ['name','email', 'age'];

    public function owner(){
        return $this->belongsTo('App\User','user_id');
    }

    public function status()
    {
        return $this->belongsTo('App\Status');
    }  
    
}

app/Http/Controllers/CandidatesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use Illuminate\Support\Enumerable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use App\Candidate;
use App\User;
use App\Department;
use App\Status;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\DB;


// full name is "App\Http\Controllers\CandidatesController"; 
class CandidatesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {        
        $candidates = Candidate::all();
        $users = User::all();
        $statuses = Status::all();        
        return view('candidates.index', compact('candidates','users', 'statuses'));
    }

    public function myCandidates()
    {        
        $userId = Auth::id();
        $user = User::findOrFail($userId);
        $candidates = $user->candidates;
        //$candidates = Candidate::all();
        $users = User::all();
        $statuses = Status::all();        
        return view('candidates.index', compact('candidates','users', 'statuses'));
    }

    public function candidatesByAge()
    {        
        $candidates = Candidate::orderBy('age','desc')->paginate();
        $users = User::all();
        $statuses = Status::all();        
        return view('candidates.index', compact('candidates','users', 'statuses'));
    }

    public function changeUser($cid, $uid = null){
        Gate::authorize('assign-user');
        $candidate = Candidate::findOrFail($cid);
        $candidate->user_id = $uid;
        $candidate->save(); 
        return back();
        //return redirect('candidates');
    }

    public function changeStatus($cid, $sid)
    {
        $candidate = Candidate::findOrFail($cid);
        if(Gate::allows('change-status', $candidate))
        {
            $from = $candidate->status->id;
            if(!Status::allowed($from,$sid)) return redirect('candidates');        
            $candidate->status_id = $sid;
            $candidate->save();
        }else{
            Session::flash('notallowed', 'You are not allowed to change the status of the user becuase you are not the owner of the user');
        }
        return back();
        //return redirect('candidates');
    }        
    
    public function changeStatusFromCadidate(Request $request){
        $cid = $request->id;
        $sid = $request->status_id;
        $candidate = Candidate::findOrFail($cid);
        if(Gate::allows('change-status', $candidate))
        {
            $from = $candidate->status->id;
            if(!Status::allowed($from,$sid)) return redirect('candidates');        
            $candidate->status_id = $sid;
            $candidate->save();
        }else{
            Session::flash('notallowed', 'You are not allowed to change the status of the user becuase you are not the owner of the user');
        }
        return redirect('candidates');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('candidates.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $candidate = new Candidate();
        //$candidate->name = $request->name; 
        //$candidate->email = $request->email;
        //$can->age = $request->age;
        $can = $candidate->create($request->all());
        $can->status_id = 1;
        $can->save();
        return redirect('candidates');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $candidate = Candidate::findOrFail($id);
        return view('candidates.information', compact('candidate'));
    }




    public function showUsers()
    {
        $users = User::all();
        return view('candidates.users', compact('users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $candidate = Candidate::findOrFail($id);
        return view('candidates.edit', compact('candidate'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       $candidate = Candidate::findOrFail($id);
       $candidate->update($request->all());
       return redirect('candidates');  
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $candidate = Candidate::findOrFail($id);
        $candidate->delete(); 
        return redirect('candidates'); 
    }

    public function statuses()
    {
        $statuses = Status::all();
        // $nextstages = DB::table('nextstages');
        // $next = $nextstages->next($stat);
        return view('candidates.statuses', compact('statuses'));
    }


}

resources/views/candidates/create.blade.php
@extends('layouts.app')

@section('title', 'Create candidate')

@section('content')
        <h1>Create candidate</h1>
        <form method = "post" action = "{{action('CandidatesController@store')}}">
        @csrf 
        <div class="form-group">
            <label for = "name">Candiadte name</label>
            <input type = "text" class="form-control" name = "name">
        </div>     
        <div class="form-group">
            <label for = "email">Candiadte email</label>
            <input type = "text" class="form-control" name = "email">
        </div> 
        <div class="form-group">
            <label for = "age">Candiadte age</label>
            <input type = "number" class="form-control" name = "age">
        </div> 
        <div>
            <input type = "submit" name = "submit" value = "Create candidate">
        </div>                    
        </form>    
@endsection

resources/views/candidates/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit candidate')

@section('content')       
       <h1>Edit candidate</h1>
        <form method = "post" action = "{{action('CandidatesController@update',$candidate->id)}}">
        @csrf
        @METHOD('PATCH')
        <div class="form-group">
            <label for = "name">Candiadte name</label>
            <input type = "text" class="form-control" name = "name" value = {{$candidate->name}}>
        </div>     
        <div class="form-group">
            <label for = "email">Candiadte email</label>
            <input type = "text" class="form-control" name = "email" value = {{$candidate->email}}>
        </div> 
        <div>
            <input type = "submit" name = "submit" value = "Update candidate">
        </div>                       
        </form>    
    </body>
</html>
@endsection

resources/views/candidates/index.blade.php
@extends('layouts.app')

@section('title', 'Candidates')

@section('content')
@if(Session::has('notallowed'))
<div class = 'alert alert-danger'>
    {{Session::get('notallowed')}}
</div>
@endif
<div><a href =  "{{url('/candidates/create')}}"> Add new candidate</a></div>
<h1>List of candidates</h1>
<table class = "table table-dark">

    <tr>
        <th>id</th><th>Name</th><th><a href = "{{route('candidates.candidatesbyage')}}">Age</a></th><th>Email</th><th>Owner</th><th>Status</th><th>Created</th><th>Updated</th>
    </tr>
    <!-- the table data -->
    @foreach($candidates as $candidate)
        
        <tr style="background-color:{{$candidate->status->name  == 'not fit' ? 'red':($candidate->status->name  == 'accepted to work' ? 'lightgreen':'')}}">
            <td>{{$candidate->id}}</td>
            <td>{{$candidate->name}}</td>
            <td>{{$candidate->age}}</td>
            <td>{{$candidate->email}}</td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @if(isset($candidate->user_id))
                          {{$candidate->owner->name}}  
                        @else
                          Assign owner
                        @endif
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    @foreach($users as $user)
                      <a class="dropdown-item" href="{{route('candidate.changeuser',[$candidate->id,$user->id])}}">{{$user->name}}</a>
                    @endforeach
                    </div>
                  </div>                
            </td>
            <td>
                <div class="dropdown">
                    @if (null != App\Status::next($candidate->status_id))    
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @if (isset($candidate->status_id))
                           {{$candidate->status->name}}
                        @else
                            Define status
                        @endif
                    </button>
                    @else 
                    {{$candidate->status->name}}
                    @endif
                                                   
                    @if (App\Status::next($candidate->status_id) != null )
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        @foreach(App\Status::next($candidate->status_id) as $status)
                         <a class="dropdown-item" href="{{route('candidates.changestatus', [$candidate->id,$status->id])}}">{{$status->name}}</a>
                        @endforeach                               
                    </div>
                    @endif
                </div>                            
            </td>                             
            <td>{{$candidate->created_at}}</td>
            <td>{{$candidate->updated_at}}</td>
            <td>
                <a href = "{{route('candidates.edit',$candidate->id)}}">Edit</a>
            </td> 
            <td>
                    <a href = "{{route('candidate.delete',$candidate->id)}}">Delete</a>
            </td>  
            <td>
                    <a href = "{{route('candidates.show',$candidate->id)}}">Information</a>
            </td>  

        </tr>
        
    @endforeach
</table> 
@endsection

resources/views/candidates/information.blade.php
@extends('layouts.app')

@section('title', 'Candidate')

@section('content')
@if(Session::has('notallowed'))
<div class = 'alert alert-danger'>
    {{Session::get('notallowed')}}
</div>
@endif
<h1>Candidate details</h1>
<table class = "table table-dark">
    <!-- the table data -->
        <tr>
            <td>Id</td><td>{{$candidate->id}}</td>
        </tr>
        <tr>
            <td>Name</td><td>{{$candidate->name}}</td>
        </tr>
        <tr>
            <td>Email</td><td>{{$candidate->email}}</td>
        </tr> 
        <tr>   
            <td>Age</td><td>{{$candidate->age}}</td>
        </tr> 
        <tr>
        <td>Owner</td>
        <td>  
            @if(isset($candidate->owner))
              {{$candidate->owner->name}}
            @else
              No owner assigned yet   
            @endif  
        <td>
        </tr>
        <tr>
           <td>Status</td> <td>{{$candidate->status->name}}</td>    
        </tr>    
        <tr>
           <td>Created</td><td>{{$candidate->created_at}}</td>
        </tr>
        <tr>
           <td>Updated</td><td>{{$candidate->updated_at}}</td>  
        </tr>    
        </table>
                                                        

                <form method="POST" action="{{ route('candidates.changestatusfromcandidate') }}">
                    @csrf  
                    <div class="form-group row">
                    <label for="department_id" class="col-md-4 col-form-label text-md-right">Move to status</label>
                    <div class="col-md-6">
                        <select class="form-control" name="status_id">                                                                         
                          @foreach (App\Status::next($candidate->status_id) as $status)
                          <option value="{{ $status->id }}"> 
                              {{ $status->name }} 
                          </option>
                          @endforeach    
                        </select>
                    </div>
                    <input name="id" type="hidden" value = {{$candidate->id}} >
                    <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Change status
                                </button>
                            </div>
                    </div>                    
                </form> 
                </div>

@endsection

resources/views/candidates/statuses.blade.php
@extends('layouts.app')

@section('title', 'statuses information')

@section('content')      

       <h1>Statuses information</h1>
        
    <table class = "table table-dark">
    <th>id</th><th>Name</th><th>Next stage1</th><th>Next stage2</th>
    @foreach($statuses as $status)
    <tr style="background-color:{{App\Status::next($status->id)  != null ? 'lightgreen':''}}">
        <td>{{$status->id}}</td>
        <td>{{$status->name}}</td>
        
        @foreach((App\Status::next($status->id)) as $sta)
        <td>
                     {{$sta->name}}
                @endforeach   
                </td> 
        @endforeach
    </table>
    
@endsection
  

        

resources/views/candidates/users.blade.php
@extends('layouts.app')

@section('title', 'users')

@section('content')      

       <h1>users information</h1>
        
    <table class = "table table-dark">
    <th>id</th><th>Name</th><th>Email</th><th>Department</th><th>Created</th><th>Updated</th>
@foreach($users as $user)
        <tr style="background-color:{{$user->messi  == '1' ? 'lightgreen':''}}">
        <td>{{$user->id}}</td>
        <td>{{$user->name}}</td>
        <td>{{$user->email}}</td>
        <td>{{$user->department->name}}</td>
        <td>{{$user->created_at}}</td>
        <td>{{$user->updated_at}}</td>
       
        
        <td>
                <a href = "{{route('users.edit',$user->id)}}">Edit</a>
        </td> 


        <td>
            <a href = "{{route('users.delete',$user->id)}}">Delete</a>
        </td> 
       
        @if(Gate::allows('assign-user')) 
        <td>
        @if($user->messi == 0)
                <a href = "{{route('users.changemessi', $user->id)}}">Deal closed</a>
                @endif     
        </td>
        @endif
           

        </tr>
 @endforeach
    </table>
@endsection
  

        